### ISSUE TITLE
JSON Arrays

### ISSUE THREAD

**Issue by CarrieRider** [apjansing/Nifi-Processors#1]
Can you make this able to handle JSON arrays?

**Comment by apjansing** [comment]
Started working on this by updating my Nifi-Tools package to handle receiving JsonElements instead of JsonObject. This allows me to check which type the content contains (JsonArray vs JsonObject).

This will allow me to have one path there JsonObjects are processed and other for JsonArrays, but I will use the methods for JsonObject flattening to flatten each of the JsonObjects in the JsonArray.

Later I will tackle if a value in a JsonObject is a JsonArray by performing the same recursive methods used to flatten them, then add them to the parent's structure.

`{name:alex,
locations:[{city:Columbia},{city:Rome}]
}`
to
`{name:alex,
locations.0.city:Columbia,
locations.1.city:Rome
}`

**Comment by apjansing** [comment]
JsonArray flattening now supported.
